# Scientists, 330000 results

#added before 2016-10
# humans without children, 256
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX schema: <http://schema.org/>
SELECT (count(distinct ?human) as ?number)
WHERE
{
  ?human wdt:P31 wd:Q5 .
  ?human wdt:P21 ?gender .
  ?human wdt:P106 ?tmp .
  ?tmp wdt:P279 wd:Q901 .
}