SELECT  ( COUNT ( ?var3  ) AS  ?var4  )WHERE {
  ?var3  <http://www.wikidata.org/prop/direct/P50>  <http://www.wikidata.org/entity/Q20895785> .
    ?var3  <http://www.wikidata.org/prop/direct/P1433>  ?var1 .
    ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var5Label .
#    FILTER (  ( (  LANG (  ?var5Label  )  =  "en" ) ) ) . 
    } 

